// This file is auto-generated by @hey-api/openapi-ts

export { adjustStock, changePrice, createProduct, deactivateProduct, getProductById, getProducts, type Options, reactivateProduct, updateProduct } from './sdk.gen';
export type { AdjustStockData, AdjustStockRequest, AdjustStockResponses, ChangePriceData, ChangePriceRequest, ChangePriceResponses, ClientOptions, CreateProductData, CreateProductRequest, CreateProductResponses, DeactivateProductData, DeactivateProductResponses, GetProductByIdData, GetProductByIdResponses, GetProductsData, GetProductsResponses, ProductCategory, ReactivateProductData, ReactivateProductResponses, UpdateProductData, UpdateProductRequest, UpdateProductResponses } from './types.gen';
