// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { AdjustStockData, AdjustStockErrors, AdjustStockResponses, ChangePriceData, ChangePriceErrors, ChangePriceResponses, CreateProductData, CreateProductErrors, CreateProductResponses, DeactivateProductData, DeactivateProductErrors, DeactivateProductResponses, GetProductByIdData, GetProductByIdErrors, GetProductByIdResponses, GetProductsData, GetProductsErrors, GetProductsResponses, ReactivateProductData, ReactivateProductErrors, ReactivateProductResponses, UpdateProductData, UpdateProductErrors, UpdateProductResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

export const getProducts = <ThrowOnError extends boolean = false>(options?: Options<GetProductsData, ThrowOnError>): RequestResult<GetProductsResponses, GetProductsErrors, ThrowOnError> => (options?.client ?? client).get<GetProductsResponses, GetProductsErrors, ThrowOnError>({ url: '/products', ...options });

export const createProduct = <ThrowOnError extends boolean = false>(options: Options<CreateProductData, ThrowOnError>): RequestResult<CreateProductResponses, CreateProductErrors, ThrowOnError> => (options.client ?? client).post<CreateProductResponses, CreateProductErrors, ThrowOnError>({
    url: '/products',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const getProductById = <ThrowOnError extends boolean = false>(options: Options<GetProductByIdData, ThrowOnError>): RequestResult<GetProductByIdResponses, GetProductByIdErrors, ThrowOnError> => (options.client ?? client).get<GetProductByIdResponses, GetProductByIdErrors, ThrowOnError>({ url: '/products/{id}', ...options });

export const updateProduct = <ThrowOnError extends boolean = false>(options: Options<UpdateProductData, ThrowOnError>): RequestResult<UpdateProductResponses, UpdateProductErrors, ThrowOnError> => (options.client ?? client).put<UpdateProductResponses, UpdateProductErrors, ThrowOnError>({
    url: '/products/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const deactivateProduct = <ThrowOnError extends boolean = false>(options: Options<DeactivateProductData, ThrowOnError>): RequestResult<DeactivateProductResponses, DeactivateProductErrors, ThrowOnError> => (options.client ?? client).post<DeactivateProductResponses, DeactivateProductErrors, ThrowOnError>({ url: '/products/{id}/deactivate', ...options });

export const reactivateProduct = <ThrowOnError extends boolean = false>(options: Options<ReactivateProductData, ThrowOnError>): RequestResult<ReactivateProductResponses, ReactivateProductErrors, ThrowOnError> => (options.client ?? client).post<ReactivateProductResponses, ReactivateProductErrors, ThrowOnError>({ url: '/products/{id}/reactivate', ...options });

export const adjustStock = <ThrowOnError extends boolean = false>(options: Options<AdjustStockData, ThrowOnError>): RequestResult<AdjustStockResponses, AdjustStockErrors, ThrowOnError> => (options.client ?? client).patch<AdjustStockResponses, AdjustStockErrors, ThrowOnError>({
    url: '/products/{id}/stock',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const changePrice = <ThrowOnError extends boolean = false>(options: Options<ChangePriceData, ThrowOnError>): RequestResult<ChangePriceResponses, ChangePriceErrors, ThrowOnError> => (options.client ?? client).patch<ChangePriceResponses, ChangePriceErrors, ThrowOnError>({
    url: '/products/{id}/price',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
