// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:5135' | (string & {});
};

export type AdjustStockRequest = {
    quantityDelta: number | string;
};

export type ChangePriceRequest = {
    newPrice: number | string;
};

export type CreateProductRequest = {
    name: string;
    sku: string;
    price: number | string;
    category: ProductCategory;
};

export type ProductCategory = 'Electronics' | 'Apparel' | 'Home' | 'Other';

export type UpdateProductRequest = {
    name: string;
    description: string;
    category: ProductCategory;
};

export type GetProductsData = {
    body?: never;
    path?: never;
    query?: {
        page?: number | string;
        pageSize?: number | string;
        isActive?: boolean;
    };
    url: '/products';
};

export type GetProductsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type CreateProductData = {
    body: CreateProductRequest;
    path?: never;
    query?: never;
    url: '/products';
};

export type CreateProductResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetProductByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/products/{id}';
};

export type GetProductByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type UpdateProductData = {
    body: UpdateProductRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/products/{id}';
};

export type UpdateProductResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type DeactivateProductData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/products/{id}/deactivate';
};

export type DeactivateProductResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type ReactivateProductData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/products/{id}/reactivate';
};

export type ReactivateProductResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type AdjustStockData = {
    body: AdjustStockRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/products/{id}/stock';
};

export type AdjustStockResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type ChangePriceData = {
    body: ChangePriceRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/products/{id}/price';
};

export type ChangePriceResponses = {
    /**
     * OK
     */
    200: unknown;
};
