// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { adjustStock, changePrice, createProduct, deactivateProduct, getProductById, getProducts, type Options, reactivateProduct, updateProduct } from '../sdk.gen';
import type { AdjustStockData, ChangePriceData, CreateProductData, DeactivateProductData, GetProductByIdData, GetProductsData, ReactivateProductData, UpdateProductData } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const getProductsQueryKey = (options?: Options<GetProductsData>) => createQueryKey('getProducts', options);

export const getProductsOptions = (options?: Options<GetProductsData>) => queryOptions<unknown, DefaultError, unknown, ReturnType<typeof getProductsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getProducts({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getProductsQueryKey(options)
});

export const createProductMutation = (options?: Partial<Options<CreateProductData>>): UseMutationOptions<unknown, DefaultError, Options<CreateProductData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<CreateProductData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createProduct({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getProductByIdQueryKey = (options: Options<GetProductByIdData>) => createQueryKey('getProductById', options);

export const getProductByIdOptions = (options: Options<GetProductByIdData>) => queryOptions<unknown, DefaultError, unknown, ReturnType<typeof getProductByIdQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getProductById({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getProductByIdQueryKey(options)
});

export const updateProductMutation = (options?: Partial<Options<UpdateProductData>>): UseMutationOptions<unknown, DefaultError, Options<UpdateProductData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<UpdateProductData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await updateProduct({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const deactivateProductMutation = (options?: Partial<Options<DeactivateProductData>>): UseMutationOptions<unknown, DefaultError, Options<DeactivateProductData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<DeactivateProductData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deactivateProduct({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const reactivateProductMutation = (options?: Partial<Options<ReactivateProductData>>): UseMutationOptions<unknown, DefaultError, Options<ReactivateProductData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<ReactivateProductData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await reactivateProduct({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const adjustStockMutation = (options?: Partial<Options<AdjustStockData>>): UseMutationOptions<unknown, DefaultError, Options<AdjustStockData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<AdjustStockData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await adjustStock({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const changePriceMutation = (options?: Partial<Options<ChangePriceData>>): UseMutationOptions<unknown, DefaultError, Options<ChangePriceData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<ChangePriceData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await changePrice({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};
