name: Build / Publish

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write
  packages: write

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: false

jobs:
  format:
    name: Format
    uses: ./.github/workflows/_format.yml

  tests:
    name: Tests
    uses: ./.github/workflows/_tests.yml

  sonarcloud:
    name: SonarCloud
    needs: [format, tests]
    uses: ./.github/workflows/_sonar.yml
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  docker:
    name: Docker
    needs: [sonarcloud]
    uses: ./.github/workflows/_docker.yml
