name: Reusable / Tests

on:
  workflow_call:

jobs:
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup .NET
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: "10.0.x"
          cache: true
          cache-dependency-path: |
            backend/**/*.csproj
            backend/Directory.Packages.props

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore -c Release

      - name: Test
        run: dotnet test tests/ProductCatalog.UnitTests --no-build -c Release --collect:"XPlat Code Coverage" --results-directory coverage/unit

      - name: Upload coverage
        uses: actions/upload-artifact@v7
        with:
          name: coverage-unit
          path: backend/coverage/unit

  integration-tests:
    name: Integration tests
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup .NET
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: "10.0.x"
          cache: true
          cache-dependency-path: |
            backend/**/*.csproj
            backend/Directory.Packages.props

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore -c Release

      - name: Test
        run: dotnet test tests/ProductCatalog.IntegrationTests --no-build -c Release --collect:"XPlat Code Coverage" --results-directory coverage/integration

      - name: Upload coverage
        uses: actions/upload-artifact@v7
        with:
          name: coverage-integration
          path: backend/coverage/integration
